# Generated by Django 5.2.7 on 2025-10-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
